# Generated by Django 5.2.8 on 2025-12-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetingApp', '0004_payment_paymentallocation_subaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
