# Generated by Django 5.2.8 on 2025-12-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetingApp', '0005_budgetitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BudgetingApp.payment')),
            ],
        ),
    ]
